lists:
  path: /api/lists
  controller: App\Controller\ListController:index
  methods: [GET]

list_create:
  path: /api/lists
  controller: App\Controller\ListController:create
  methods: [POST]

list_delete:
  path: /api/lists/{id}
  controller: App\Controller\ListController:delete
  methods: [DELETE]

list_update:
  path: /api/lists/{id}/update
  controller: App\Controller\ListController:update
  methods: [POST]
